#ifndef __MAIN_H_
#define __MAIN_H_

// Colors
#define TEXT_COLOR 0xE6
#define ACCENT_COLOR 0x80
#define MENU_COLOR 0x00
#define SUBMENU_COLOR 0x4A
#define TRANSP_COLOR 0xF8
#define RED_COLOR 0xE8
#define GREEN_COLOR 0x25
#define YELLOW_COLOR 0xE7
#define GRAY_COLOR 0xAC
#define SELECTED_COLOR 0xE3

// Prices
#define PRICE_LEATHER_HELMET 10
#define PRICE_LEATHER_TUNIC 10
#define PRICE_LEATHER_BOOTS 10
#define PRICE_IRON_HELMET 50
#define PRICE_CHAIN_SHIRT 50
#define PRICE_CHAIN_BOOTS 50
#define PRICE_STEEL_HELMET 100
#define PRICE_STEEL_CHESTPLATE 100
#define PRICE_STEEL_BOOTS 100
#define PRICE_DRAGON_HELMET 500
#define PRICE_DRAGON_CHESTPLATE 500
#define PRICE_DRAGON_BOOTS 500
#define PRICE_CLUB 10
#define PRICE_IRON_SWORD 50
#define PRICE_STEEL_SWORD 100
#define PRICE_DRAGON_SWORD 500
#define PRICE_BASIC_BOW 10
#define PRICE_RECURVE_BOW 50
#define PRICE_COMPOUND_BOW 100
#define PRICE_DRAGON_BOW 500
#define PRICE_SMALL_POTION 10
#define PRICE_MEDIUM_POTION 50
#define PRICE_LARGE_POTION 150

#define TILEMAP_TILE_SIZE 32

#define TILEMAP_WIDTH       40
#define TILEMAP_HEIGHT      200

#define TILEMAP_DRAW_WIDTH  10
#define TILEMAP_DRAW_HEIGHT 7

#define TILEMAP_MAX_X (TILEMAP_WIDTH * TILEMAP_TILE_SIZE)
#define TILEMAP_MAX_Y (TILEMAP_HEIGHT * TILEMAP_TILE_SIZE)

#endif
